### ISSUE TITLE
Crash when clicking "Learn More" or the ad

### ISSUE THREAD

**Issue by Joadar** [googleads/googleads-ima-android#116]
We found this edge case where the user doesn't have any browser on his device, user click on the ad or the "Learn More" link that lead to a crash.

### Steps to reproduce
- Disable your browser from your device
-- Select your default browser
-- Go to App Info
-- Disable
- Launch ExoPlayerExample on your device
- Play the video
- Click "Learn More"
- Crash

### Some solutions suggested
- We could disable the CLICK event when user doesn't have any app to open links
- We could display a Toast message informing the user
- We could open a new screen with a Webview if there is no browser
- We could hide the "Learn More" link if there is no browser
- ...

### Stacktrace
```
Process: com.google.ads.interactivemedia.v3.samples.exoplayerexample, PID: 18283
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://pubads.g.doubleclick.net/... flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:432)
at com.google.ads.interactivemedia.v3.internal.akk.a(IMASDK:5)
at com.google.ads.interactivemedia.v3.internal.ahs.h(IMASDK:1)
at com.google.ads.interactivemedia.v3.internal.ain.k(IMASDK:22)
at com.google.ads.interactivemedia.v3.internal.ait.f(IMASDK:5)
at com.google.ads.interactivemedia.v3.internal.aiq.shouldOverrideUrlLoading(IMASDK:2)
at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-556305833:89)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loopOnce(Looper.java:161)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)```

**Comment by Joadar** [comment]
Thank you @Kiro705 for your fast answer.

I just create a [new conversation](https://groups.google.com/g/ima-sdk/c/3yClrQrkPPg) in the support forum. I could not find a method to disable the IMA handled clickthrough.

Regards,
Jonathan

**Comment by Kiro705** [comment]
Hi @Joadar ,

Thank you for raising the thread on the support forum. I believe. fix for the issue should be included in the next Android SDK release. I'm going to close this issue here, but feel free to follow up on the other thread.

Thank you,
Jackson
IMA SDK team
