### ISSUE TITLE
Can't play HLS or clear DASH  mime types in BasicExample

### ISSUE THREAD

**Issue by giladna** [googleads/googleads-ima-android#12]
Hi
I have changed the basic example which uses Exo Player insdie IMA SDK
by giving the init renderingSetting  with HLS mime type

I guess you do something similar to googlemediaramework:  
  Video adVideo = new Video(adTagUrl.toString(), Video.VideoType.MP4);

by giving MP4 which does not fit application/x-mpegURL 
or application/dash+xml which I get not supported error   

AdsRenderingSettings renderingSettings = ImaSdkFactory.getInstance().createAdsRenderingSettings();

                    List<String> mimeTypes = new ArrayList<>();
                    mimeTypes.add("application/x-mpegURL");
                    renderingSettings.setMimeTypes(mimeTypes);
                    renderingSettings.setUiElements(Collections.<UiElement>emptySet());
                    mAdsManager.init(renderingSettings); 

I get the following Exception for my adtag url:

12-06 22:31:44.307 28152-28152/com.google.ads.interactivemedia.v3.samples.videoplayerapp E/IMA SDK: Load Error from SampleSource:0:com.google.ads.interactivemedia.v3.a.c.h$e: None of the available extractors (f, e, f, c, b, o, b, b, l, a) could read the stream.
12-06 22:31:44.316 28152-28290/com.google.ads.interactivemedia.v3.samples.videoplayerapp E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                                                  com.google.ads.interactivemedia.v3.a.f: com.google.ads.interactivemedia.v3.a.c.h$e: None of the available extractors (f, e, f, c, b, o, b, b, l, a) could read the stream.
                                                                                                                      at com.google.ads.interactivemedia.v3.a.u.a(IMASDK:262)
                                                                                                                      at com.google.ads.interactivemedia.v3.a.u.s(IMASDK:148)
                                                                                                                      at com.google.ads.interactivemedia.v3.a.i.e(IMASDK:273)
                                                                                                                      at com.google.ads.interactivemedia.v3.a.i.handleMessage(IMASDK:203)
                                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                                      at com.google.ads.interactivemedia.v3.a.f.o.run(IMASDK:40)
                                                                                                                   Caused by: com.google.ads.interactivemedia.v3.a.c.h$e: None of the available extractors (f, e, f, c, b, o, b, b, l, a) could read the stream.
                                                                                                                      at com.google.ads.interactivemedia.v3.a.c.h$c.a(IMASDK:898)
                                                                                                                      at com.google.ads.interactivemedia.v3.a.c.h$b.c(IMASDK:828)
                                                                                                                      at com.google.ads.interactivemedia.v3.a.e.l$b.run(IMASDK:222)
                                                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                                      at java.lang.Thread.run(Thread.java:818)
12-06 22:31:44.316 28152-28152/com.google.ads.interactivemedia.v3.samples.videoplayerapp E/IMA SDK: Player Error:com.google.ads.interactivemedia.v3.a.f: com.google.ads.interactivemedia.v3.a.c.h$e: None of the available extractors (f, e, f, c, b, o, b, b, l, a) could read the stream.
12-06 22:31:44.369 28152-28152/com.google.ads.interactivemedia.v3.samples.videoplayerapp E/ImaExample: Ad Error: There was an error playing the video ad.
12-06 22:31:44.384 28152

**Comment by ypavlotsky** [comment]
Judging by the error, your ExoPlayer isn't set up to play the media you're getting back from the ad. Your AdRenderingSettings code should be enough to tell the SDK choose HLS files, so I would double-check the ad tag and see what it's returning to make sure you're getting back an HLS file. You can also mail our support, ima-sdk-support@google.com with your ad tag.

**Comment by giladna** [comment]
But the Exo Player is internal in the IMA SDK 
As I read in your post

**Comment by ypavlotsky** [comment]
Ah, didn't realize you were using SDK-owned playback. Could you email our support alias with your ad tag, I'll take a look.

**Comment by giladna** [comment]
sure

**Comment by giladna** [comment]
Did you get it?

**Comment by ypavlotsky** [comment]
Thanks for providing your ad tag. The issue is on our end because the SDK-Owned player doesn't support HLS ads at this time. It also doesn't support DASH ads.

**Comment by giladna** [comment]
Thanks,
Do you have any estimation for supporting it?

**Comment by ypavlotsky** [comment]
We don't have any current plans for supporting it in SDK-Owned player, but I can discuss supporting this use case with the team.

For now, you can use custom playback to support HLS ads.

**Comment by itaykinnrot** [comment]
What is IMA recommendations here? Use adaptive for ads or not?

**Comment by ypavlotsky** [comment]
You can support HLS / DASH with the SDK, but you'll need to use custom playback. You can take a look at the [AdvancedExample](https://github.com/googleads/googleads-ima-android/tree/master/AdvancedExample) in this repo for an example of implementing custom playback.
