### ISSUE TITLE
Abstract classes can't be instantiated when using full R8

### ISSUE THREAD

**Issue by davidtrpchevski** [googleads/googleads-ima-android#123]
After upgrading to AGP 8.0 and JDK 17, android.enableR8.fullMode flag is set to true by default.

This is the error log that we get when opening any app:

```
Invalid internal message. Message could not be be parsed: {"type":"initialized","sid":"*","data":"{\"adTimeUpdateMs\":200,\"adUiStyle\":\"webViewUi\",\"appSetIdTimeoutMs\":150,\"consentSettingsConfig\":{\"consentKeys\":[\"IABUSPrivacy_String\",\"IABTCF_gdprApplies\",\"IABTCF_TCString\",\"IABTCF_AddtlConsent\"],\"consentKeyTypes\":{\"IABUSPrivacy_String\":\"String\",\"IABTCF_gdprApplies\":\"Number\",\"IABTCF_TCString\":\"String\",\"IABTCF_AddtlConsent\":\"String\"}},\"enableGks\":true,\"enableTrustlessGksBc\":true,\"enableTrustlessGksDai\":true,\"enableInstrumentation\":false,\"enablePaidV1\":true,\"enablePaidV2\":true,\"jsConsentCheckRequiredParameters\":[\"gdpr\"],\"paidV1Ttl\":2505600,\"paidV2Ttl\":33696000,\"espAdapters\":[\"com.google.ads.interactivemedia.fakeespadapter.FakeMediationAdapter\"],\"gksFirstPartyAdServers\":[\"pubads.g.doubleclick.net\",\"bid.g.doubleclick.net\",\"googleads.g.doubleclick.net\"],\"gksTimeoutMs\":500,\"espAdapterTimeoutMs\":500,\"jsVersion\":\"3.357.0\",\"useAndroidAdshieldV2\":false,\"platformSignalCollectorTimeoutMs\":500}","name":"webViewLoaded"}, Message Type: 4
                                                                                                    com.google.ads.interactivemedia.v3.internal.zzse: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.google.ads.interactivemedia.v3.impl.data.JavaScriptMsgDataWebViewCompat
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zztq.zza(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:1)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzvq.zza(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:1)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzvo.read(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:3)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzry.zzd(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:4)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzry.zze(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:5)
                                                                                                    	at com.google.ads.interactivemedia.v3.impl.JavaScriptMessage.fromWebViewCompatMessage(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:1)
                                                                                                    	at com.google.ads.interactivemedia.v3.impl.JavaScriptWebView.receiveJavaScriptMsg(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:2)
                                                                                                    	at com.google.ads.interactivemedia.v3.impl.zzav.onPostMessage(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:2)
                                                                                                    	at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:55)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy11.onPostMessage(Unknown Source)
                                                                                                    	at org.chromium.android_webview.WebMessageListenerHolder.onPostMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495151534:55)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7886)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

```
Invalid internal message. Message could not be be parsed: {"type":"omidReady","sid":"*","name":"omid"}, Message Type: 4
                                                                                                    com.google.ads.interactivemedia.v3.internal.zzse: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.google.ads.interactivemedia.v3.impl.data.JavaScriptMsgDataWebViewCompat
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zztq.zza(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:1)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzvq.zza(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:1)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzvo.read(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:3)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzry.zzd(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:4)
                                                                                                    	at com.google.ads.interactivemedia.v3.internal.zzry.zze(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:5)
                                                                                                    	at com.google.ads.interactivemedia.v3.impl.JavaScriptMessage.fromWebViewCompatMessage(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:1)
                                                                                                    	at com.google.ads.interactivemedia.v3.impl.JavaScriptWebView.receiveJavaScriptMsg(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:2)
                                                                                                    	at com.google.ads.interactivemedia.v3.impl.zzav.onPostMessage(com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1:2)
                                                                                                    	at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:55)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy11.onPostMessage(Unknown Source)
                                                                                                    	at org.chromium.android_webview.WebMessageListenerHolder.onPostMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495151534:55)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7886)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

This is run in debug mode so you can check which class is troublesome. In both errors the error log is similar:

```
Invalid internal message. Message could not be be parsed: {"type":"omidReady","sid":"*","name":"omid"}, Message Type: 4
                                                                                                    com.google.ads.interactivemedia.v3.internal.zzse: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.google.ads.interactivemedia.v3.impl.data.JavaScriptMsgDataWebViewCompat

```

**Comment by davidtrpchevski** [comment]
Forgot to mention, the mapping for zzse

com.google.ads.interactivemedia.v3.internal.zzse -> com.google.ads.interactivemedia.v3.internal.zzse:
# {"id":"sourceFile","fileName":"com.google.ads.interactivemedia.v3:interactivemedia@@3.30.1"}
    1:1:void <init>(java.lang.String) -> <init>
    2:2:void <init>(java.lang.String,java.lang.Throwable) -> <init>
    3:3:void <init>(java.lang.Throwable) -> <init>

**Comment by davidtrpchevski** [comment]
Additional details, adding these lines to proguard-rules works, but I don't think it's the proper solution

```
-keep interface com.google.ads.interactivemedia.v3.** { *; }
-keep class com.google.ads.interactivemedia.v3.** { *; }
```

**Comment by davidtrpchevski** [comment]
Well, I got my answer from the official sample. Closing this one since it's intended behaviour.

![image](https://user-images.githubusercontent.com/13114412/234386908-70d5b0ba-f150-4465-a079-4a0416a1df14.png)
