### ISSUE TITLE
targetSDK 34，IMA SDK3.34.0，Android7 crash

### ISSUE THREAD

**Issue by zhqchen** [googleads/googleads-ima-android#149]
I use IMA SDK v3.34.0，after I upgrade my app's targetSDK 34，Android 7 phones crash！
      
          Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
       at com.google.ads.interactivemedia.v3.internal.zzok.zza(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:1)
       at com.google.ads.interactivemedia.v3.impl.zzal.zza(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:6)
       at com.google.ads.interactivemedia.v3.impl.zzbv.zzg(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:3)
       at com.google.ads.interactivemedia.v3.impl.zzbv.zze(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:2)
       at com.google.ads.interactivemedia.v3.impl.zzz.zzc(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:11)
       at com.google.ads.interactivemedia.v3.impl.zzaz.zzm(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:47)
       at com.google.ads.interactivemedia.v3.impl.zzbj.zzi(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:7)
       at com.google.ads.interactivemedia.v3.impl.zzbf.onPostMessage(com.google.ads.interactivemedia.v3:interactivemedia@@3.34.0:2)
       at androidx.webkit.internal.WebMessageListenerAdapter.onPostMessage(WebMessageListenerAdapter.java:55)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:162)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at $Proxy26.onPostMessage()
       at d55.run(chromium-Monochrome.aab-stable-604519321:99)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6173)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by Kiro705** [comment]
Hello @zhqchen ,

Thank you for raising this issue. The IMA SDK team is aware of it and looking to fix the issue in a future release.

Because of that, the team will keep the current `minSdkVersion` as 21 in its sample apps.

Please let me know if you have any questions.

Thank you,
Jackson
IMA SDK team
