### ISSUE TITLE
AudioPlayerExample not working

### ISSUE THREAD

**Issue by kunweiwu** [googleads/googleads-ima-android#61]
I just run app in my physical device, ASUS ZenFone Max Pro, OS = Android 9 
code version = commit 8afe224 at Mar9, 2021.

When i press button "REQUEST AD" something wrong, and audio ad did not hear.

This is my log :

```
I/ayerexample.ap: The ClassLoaderContext is a special shared library.
I/ayerexample.ap: The ClassLoaderContext is a special shared library.
I/ayerexample.ap: The ClassLoaderContext is a special shared library.
I/ayerexample.ap: The ClassLoaderContext is a special shared library.
D/hw: File /data/user/0/com.google.ads.interactivemedia.v3.samples.audioplayerexample.app/cache/1613498354782.dex not found. No need for deletion
W/ayerexample.ap: Unknown chunk type '200'.
W/ayerexample.ap: Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/IMASDK: Invalid internal message. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/activityMonitor?type=getPageSignals&sid=762e25a1-cfdc-456e-8d8b-b778c0044989&dt=1615429316405
I/ImaService: Event: LOADED
I/ImaService: Event: CONTENT_PAUSE_REQUESTED
I/ImaService: Event: AD_BUFFERING
I/ImaService: Event: AD_BUFFERING
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
    NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.google.h264.decoder, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
    NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
    NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.google.h264.decoder, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
    NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
    NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.google.h264.decoder, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
I/OMXClient: IOmx service obtained
D/SurfaceUtils: connecting to surface 0x77dda26010, reason connectToSurface
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 16747521
D/SurfaceUtils: disconnecting from surface 0x77dda26010, reason connectToSurface(reconnect)
    connecting to surface 0x77dda26010, reason connectToSurface(reconnect)
I/ExtendedACodec: setupVideoDecoder()
I/ExtendedACodec: Decoder will be in frame by frame mode
D/SurfaceUtils: set up nativeWindow 0x77dda26010 for 512x288, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal: buffer descriptor with invalid usage bits 0x2000
W/MapperHal: buffer descriptor with invalid usage bits 0x2000
W/MapperHal: buffer descriptor with invalid usage bits 0x2000
W/MapperHal: buffer descriptor with invalid usage bits 0x2000
W/MapperHal: buffer descriptor with invalid usage bits 0x2000
W/MapperHal: buffer descriptor with invalid usage bits 0x2000
E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
    signalError(omxError 0x80001009, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
D/SurfaceUtils: disconnecting from surface 0x77dda26010, reason disconnectFromSurface
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
    NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.google.h264.decoder, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.F40015, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [ASUS_X00T_8, ASUS_X00TDB, asus, 28]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.F40015, -1, null, [512, 288, 24.968906], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1392)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:839)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:82)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1779)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2131)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:142)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:887)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:880)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:482)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1607)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1349)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1313)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:570)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77d67fb780
W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 27 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77d67fb980
W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 26 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77d67fba80
W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 25 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77d67fbb00
W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 24 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77d67fbb80
W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 23 to native window
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77d67fbc00
W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 22 to native window
I/ayerexample.ap: Thread[3,tid=16361,WaitingInMainSignalCatcherLoop,Thread*=0x77f7816400,peer=0x13180110,"Signal Catcher"]: reacting to signal 3
I/ayerexample.ap: Wrote stack traces to '[tombstoned]'
E/ImaService: Ad Error: VAST media file loading reached a timeout of 8 seconds.
I/ImaService: Event: CONTENT_RESUME_REQUESTED
I/ImaService: Event: ALL_ADS_COMPLETED
I/OMXClient: IOmx service obtained
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config priority (err -2147483648)
W/ExtendedACodec: Failed to get extension for extradata parameter
```

**Comment by Kiro705** [comment]
Hello @kunweiwu ,

Is this issue still reproducible in the [latest release](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0)? If so, please feel free to reopen this issue with any other steps needed to reproduce the issue.
